spring.application.name=blogger-box-backend

spring.datasource.url=jdbc:postgresql://db.wnnhirckhlrblknunutl.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=MSvdTFWSiHRjws2M
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true